<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",406,435);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",474,532);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",537,572);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",796,825);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n									<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"datetime\">[[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</span></li>\r\n                                ",931,1168);
$z[6][4]['pagesize']="19";
$z[7]=Array("pagelist","",1234,1305);
$z[7][4]['istitem']="index,pre,next,end,option,info,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1400,1437);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("global","",1607,1639);
$z[9][4]['name']="cfg_templets_skin";

?>