<?php
$z[0]=Array("field","",93,112);
$z[0][4]['name']="title";
$z[1]=Array("global","",113,139);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",180,207);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",247,277);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",283,318);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type","  \r\n			<h2 class=\"news_t\">[field:typename/]</h2>\r\n		",837,924);
$z[5][4]['typeid']="10";
$z[6]=Array("include","",1220,1255);
$z[6][4]['filename']="foot.htm";

?>