<li>
								<div class="leftimg">
									<a  href="[field:arcurl /]"><img src="[field:litpic/]" data-original="[field:litpic/]" /></a>
								</div>
								<div class="rightinfo">
									<a href="[field:arcurl /]"><span class="articletitle">[field:title/]</span></a>
									<p class="articleinfo">[field:description function='cn_substr(@me,150)'/]......</p>
								</div>
							</li>