<?php
$z[0]=Array("global","",754,780);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",821,848);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",888,918);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",5627,5664);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("type","[field:typename /]",6571,6623);
$z[4][4]['typeid']="1";
$z[5]=Array("arclist","\r\n                        	<li>\r\n								<a href=\"[field:arcurl/]\"><span class=\"txt\">[field:title/]</span><span class=\"time\">[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span></a>\r\n							</li>\r\n							",6702,6993);
$z[5][4]['typeid']="1";
$z[5][4]['titlelen']="26";
$z[5][4]['row']="6";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("type","[field:typename /]",7106,7158);
$z[6][4]['typeid']="2";
$z[7]=Array("arclist","\r\n                        	<li>\r\n								<div class=\"leftimg\">\r\n									<a  href=\"[field:arcurl /]\"><img src=\"[field:litpic/]\" data-original=\"[field:litpic/]\" /></a>\r\n								</div>\r\n								<div class=\"rightinfo\">\r\n									<a href=\"[field:arcurl /]\"><span class=\"articletitle\">[field:title/]</span></a>\r\n									<p class=\"articleinfo\">[field:description function='cn_substr(@me,150)'/]......</p>\r\n								</div>\r\n							</li>\r\n							",7241,7762);
$z[7][4]['typeid']="2";
$z[7][4]['titlelen']="26";
$z[7][4]['row']="6";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("type","[field:typename /]",7868,7920);
$z[8][4]['typeid']="3";
$z[9]=Array("arclist","\r\n                    	<div class=\"tukucard\">\r\n							<a  href=\"[field:arcurl /]\">\r\n								<div class=\"tukupic\"><img src=\"[field:litpic/]\"  data-original=\"[field:litpic/]\" /></div>\r\n								<span>[field:title/]</span>\r\n							</a>\r\n						</div>\r\n						",7975,8310);
$z[9][4]['typeid']="3";
$z[9][4]['titlelen']="50";
$z[9][4]['row']="2";
$z[9][4]['orderby']="pubdate";
$z[10]=Array("include","",8373,8412);
$z[10][4]['filename']="footer_m.htm";

?>