<?php
$z[0]=Array("field","",754,776);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",817,839);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",879,930);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",4722,4759);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",5540,5569);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                        	<li>\r\n								<a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n							</li>\r\n							",5663,5817);
$z[6]=Array("include","",6058,6097);
$z[6][4]['filename']="footer_m.htm";

?>