<?php
$z[0]=Array("field","",754,776);
$z[0][4]['name']="seotitle";
$z[1]=Array("field","",817,839);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",879,930);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",4716,4753);
$z[3][4]['filename']="head_m.htm";
$z[4]=Array("field","",5534,5563);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                        	<li>\r\n								<a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]</a>\r\n							</li>\r\n							",5706,5869);
$z[6]=Array("include","",6110,6149);
$z[6][4]['filename']="footer_m.htm";

?>