<?php
$z[0]=Array("global","",65,91);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",132,159);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",199,229);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",235,270);
$z[3][4]['filename']="head.htm";
$z[4]=Array("global","",405,437);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",523,555);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("arclist","\r\n				<li>\r\n					<a href='[field:arcurl/]' title='[field:title /]'>\r\n						<img src='[field:litpic/]' height=\"130\" width=\"218\" alt=\"\">\r\n						<h5>[field:title/]</h5>\r\n						<p>\r\n							<span>[field:shorttitle/]</span>\r\n						</p>\r\n					</a>\r\n				</li>\r\n				",764,1101);
$z[6][4]['typeid']="1";
$z[6][4]['titlelen']="50";
$z[6][4]['row']="5";
$z[6][4]['orderby']="click";
$z[7]=Array("arclist","\r\n					<li>\r\n						<span class=\"time\">[field:pubdate function='strftime(\"%m-%d\",@me)'/]</span>\r\n						<a href=\"[field:arcurl/]\">[field:title/]</a>\r\n					</li>\r\n                  ",1495,1754);
$z[7][4]['orderby']="pubdate";
$z[7][4]['titlelen']="30";
$z[7][4]['typeid']="2";
$z[7][4]['row']="3";
$z[8]=Array("arclist","\r\n						<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                        ",2187,2357);
$z[8][4]['orderby']="hot";
$z[8][4]['titlelen']="30";
$z[8][4]['typeid']="6,7,8,9";
$z[8][4]['row']="4";
$z[9]=Array("include","",2769,2804);
$z[9][4]['filename']="foot.htm";

?>