<?php
$z[0]=Array("global","",73,105);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",138,170);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("channelartlist","\r\n				<li>\r\n                	<a href='{dede:field name='typeurl'/}'>\r\n						{dede:field name='typename'/}\r\n					</a>\r\n                </li>\r\n                ",272,498);
$z[2][4]['typeid']="1,2,3,4";
$z[2][4]['row']="4";

?>