<?php
$z[0]=Array("list","<url>	\r\n   <loc>[field:arcurl function=\"Gmapurl(@me)\"/]</loc> 	\r\n   <title>[field:title function=\"HtmlReplace(@me)\"/]</title>	\r\n   <news:news>	\r\n  <news:keywords>[field:keywords/]</news:keywords>	\r\n <news:publication_date>[field:senddate function=\"strftime(\"%Y-%m-%d\",@me)\"/]</news:publication_date>	\r\n </news:news>	\r\n</url>",0,422);
$z[0][4]['pagesize']="500";
$z[0][4]['col']="1";
$z[0][4]['titlelen']="60";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";

?>