<?php
$z[0]=Array("include","",404,439);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",699,728);
$z[1][4]['name']="position";
$z[2]=Array("global","",1085,1117);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("list","\r\n									<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"datetime\">[[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</span></li>\r\n                              	  ",1336,1574);
$z[3][4]['pagesize']="19";
$z[4]=Array("pagelist","",1640,1711);
$z[4][4]['istitem']="index,pre,next,end,option,info,";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",1825,1862);
$z[5][4]['filename']="footer.htm";
$z[6]=Array("global","",2011,2043);
$z[6][4]['name']="cfg_templets_skin";

?>