<?php
$z[0]=Array("include","",404,439);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",637,669);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1040,1072);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",1265,1294);
$z[3][4]['name']="position";
$z[4]=Array("list","\r\n									<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"datetime\">[[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</span></li>\r\n                              	  ",1379,1617);
$z[4][4]['pagesize']="19";
$z[5]=Array("pagelist","",1683,1754);
$z[5][4]['istitem']="index,pre,next,end,option,info,";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1868,1905);
$z[6][4]['filename']="footer.htm";
$z[7]=Array("global","",2054,2086);
$z[7][4]['name']="cfg_templets_skin";

?>