<?php
$z[0]=Array("pagelist","@me=trim(strip_tags(@me));if (is_numeric(@me)){if (@me!='1') @me='_ตฺ'.@me.'าณ';else @me=\"\";}else @me=\"\";",271,451);
$z[0][4]['listitem']="pageno";
$z[0][4]['listsize']="0";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","",452,485);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("freelist","",538,554);
$z[3]=Array("pagelist","",557,628);
$z[3][4]['listitem']="info,index,end,pre,next,pageno";
$z[3][4]['listsize']="5";

?>