<?php
$z[0]=Array("field","",319,338);
$z[0][4]['name']="title";
$z[1]=Array("global","",339,365);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",406,433);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",473,503);
$z[3][4]['name']="cfg_description";
$z[4]=Array("include","",509,544);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",768,797);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n									<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a><span class=\"datetime\">[[field:pubdate function=\"GetDateTimeMK(@me)\" /]]</span></li>\r\n                                ",903,1140);
$z[6][4]['pagesize']="19";
$z[7]=Array("pagelist","",1206,1277);
$z[7][4]['istitem']="index,pre,next,end,option,info,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",1372,1409);
$z[8][4]['filename']="footer.htm";
$z[9]=Array("global","",1579,1611);
$z[9][4]['name']="cfg_templets_skin";

?>