<?php $urls = array(
    'http://shuihu.789game.com/sitemap.html',
	'http://shuihu.789game.com/m/',
	'http://shuihu.789game.com/xinwengonggao/2.html',
'http://shuihu.789game.com/xinwengonggao/3.html',
'http://shuihu.789game.com/xinwengonggao/4.html',
'http://shuihu.789game.com/xinwengonggao/5.html',
'http://shuihu.789game.com/xinwengonggao/6.html',
'http://shuihu.789game.com/xinwengonggao/7.html',
'http://shuihu.789game.com/xinwengonggao/8.html',
'http://shuihu.789game.com/xinwengonggao/9.html',
'http://shuihu.789game.com/xinwengonggao/10.html',
'http://shuihu.789game.com/xinwengonggao/11.html',
'http://shuihu.789game.com/xinwengonggao/24.html',
'http://shuihu.789game.com/xinwengonggao/25.html',
'http://shuihu.789game.com/xinwengonggao/27.html',
'http://shuihu.789game.com/xinwengonggao/41.html',
'http://shuihu.789game.com/xinwengonggao/42.html',
'http://shuihu.789game.com/xinwengonggao/48.html',
'http://shuihu.789game.com/xinwengonggao/47.html',
'http://shuihu.789game.com/youxigonglue/12.html',
'http://shuihu.789game.com/youxigonglue/13.html',
'http://shuihu.789game.com/youxigonglue/14.html',
'http://shuihu.789game.com/youxigonglue/15.html',
'http://shuihu.789game.com/youxigonglue/16.html',
'http://shuihu.789game.com/youxigonglue/17.html',
'http://shuihu.789game.com/youxigonglue/18.html',
'http://shuihu.789game.com/youxigonglue/19.html',
'http://shuihu.789game.com/youxigonglue/20.html',
'http://shuihu.789game.com/youxigonglue/21.html',
'http://shuihu.789game.com/youxigonglue/22.html',
'http://shuihu.789game.com/youxigonglue/23.html',
'http://shuihu.789game.com/youxigonglue/28.html',
'http://shuihu.789game.com/youxigonglue/29.html',
'http://shuihu.789game.com/youxigonglue/30.html',
'http://shuihu.789game.com/youxigonglue/31.html',
'http://shuihu.789game.com/youxigonglue/32.html',
'http://shuihu.789game.com/youxigonglue/33.html',
'http://shuihu.789game.com/youxigonglue/34.html',
'http://shuihu.789game.com/youxigonglue/35.html',
'http://shuihu.789game.com/youxigonglue/36.html',
'http://shuihu.789game.com/youxigonglue/37.html',
'http://shuihu.789game.com/youxigonglue/38.html',
'http://shuihu.789game.com/youxigonglue/39.html',
'http://shuihu.789game.com/youxigonglue/40.html',
'http://shuihu.789game.com/youxigonglue/41.html',
'http://shuihu.789game.com/youxigonglue/42.html',
'http://shuihu.789game.com/youxigonglue/43.html',
'http://shuihu.789game.com/youxigonglue/44.html',
'http://shuihu.789game.com/youxigonglue/45.html',
'http://shuihu.789game.com/youxigonglue/46.html',
'http://shuihu.789game.com/youxigonglue/47.html',
'http://shuihu.789game.com/youxigonglue/48.html',
'http://shuihu.789game.com/youxigonglue/49.html',
'http://shuihu.789game.com/youxigonglue/50.html',
'http://shuihu.789game.com/youxigonglue/51.html',
'http://shuihu.789game.com/youxigonglue/52.html',
'http://shuihu.789game.com/youxigonglue/53.html',
'http://shuihu.789game.com/youxigonglue/54.html',
'http://shuihu.789game.com/youxigonglue/55.html',
'http://shuihu.789game.com/youxigonglue/56.html',
'http://shuihu.789game.com/youxigonglue/57.html',
'http://shuihu.789game.com/youxigonglue/58.html',
'http://shuihu.789game.com/youxigonglue/59.html',
'http://shuihu.789game.com/youxigonglue/60.html',

'http://shuihu.789game.com/m/',
'http://shuihu.789game.com/m/youxizhuanqu/2.html',
'http://shuihu.789game.com/m/youxizhuanqu/3.html',
'http://shuihu.789game.com/m/youxizhuanqu/4.html',
'http://shuihu.789game.com/m/youxizhuanqu/5.html',
'http://shuihu.789game.com/m/youxizhuanqu/6.html',
'http://shuihu.789game.com/m/youxizhuanqu/7.html',
'http://shuihu.789game.com/m/youxizhuanqu/8.html',
'http://shuihu.789game.com/m/youxizhuanqu/9.html',
'http://shuihu.789game.com/m/youxizhuanqu/10.html',
'http://shuihu.789game.com/m/youxizhuanqu/11.html',
'http://shuihu.789game.com/m/youxizhuanqu/12.html',
'http://shuihu.789game.com/m/youxizhuanqu/13.html',
'http://shuihu.789game.com/m/youxizhuanqu/14.html',
'http://shuihu.789game.com/m/youxizhuanqu/15.html',
'http://shuihu.789game.com/m/youxizhuanqu/16.html',
'http://shuihu.789game.com/m/youxizhuanqu/17.html',
'http://shuihu.789game.com/m/youxizhuanqu/18.html',
'http://shuihu.789game.com/m/youxizhuanqu/19.html',
'http://shuihu.789game.com/m/youxizhuanqu/20.html',
'http://shuihu.789game.com/m/youxizhuanqu/21.html',
'http://shuihu.789game.com/m/youxizhuanqu/22.html',
'http://shuihu.789game.com/m/youxizhuanqu/23.html',
'http://shuihu.789game.com/m/youxizhuanqu/24.html',
'http://shuihu.789game.com/m/youxizhuanqu/25.html',
'http://shuihu.789game.com/m/youxizhuanqu/26.html',
'http://shuihu.789game.com/m/youxizhuanqu/27.html',
'http://shuihu.789game.com/m/youxizhuanqu/28.html',
'http://shuihu.789game.com/m/youxizhuanqu/29.html',
'http://shuihu.789game.com/m/youxizhuanqu/30.html',
'http://shuihu.789game.com/m/youxizhuanqu/31.html',
'http://shuihu.789game.com/m/youxizhuanqu/32.html',
'http://shuihu.789game.com/m/youxizhuanqu/33.html',
'http://shuihu.789game.com/m/youxizhuanqu/34.html',
'http://shuihu.789game.com/m/youxizhuanqu/35.html',
'http://shuihu.789game.com/m/youxizhuanqu/36.html',



  
);
$api = 'http://data.zz.baidu.com/urls?site=shuihu.789game.com&token=e1qB73AxybvCS46s';
$ch = curl_init();
$options =  array(
    CURLOPT_URL => $api,
    CURLOPT_POST => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POSTFIELDS => implode("\n", $urls),
    CURLOPT_HTTPHEADER => array('Content-Type: text/plain'),
);
curl_setopt_array($ch, $options);
$result = curl_exec($ch);
echo $result;
?>
